# Generated by Django 2.2.3 on 2021-07-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('email', models.CharField(max_length=40, verbose_name='Correo')),
                ('mensaje', models.TextField(max_length=200, verbose_name='Mensaje')),
                ('image', models.ImageField(upload_to='productos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'ordering': ['-created'],
            },
        ),
    ]
