# Generated by Django 2.2.3 on 2021-07-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='image',
        ),
    ]
