# Generated by Django 3.2.4 on 2021-07-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210706_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='idComponente',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='idMarca',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
