# Generated by Django 2.2.3 on 2021-07-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210706_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, verbose_name='Usuario')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('genero', models.IntegerField(choices=[[0, 'masculino'], [1, 'femenino'], [2, 'no binario']])),
                ('comuna', models.IntegerField(choices=[[0, 'santiago'], [1, 'san joaquin'], [2, 'macul'], [3, 'quinta normal'], [4, 'cerro navia'], [5, 'ñuñoa'], [6, 'renca'], [7, 'las condes']])),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
