# Generated by Django 2.2.3 on 2021-07-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210707_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechanacimiento',
        ),
    ]
